const $=s=>document.querySelector(s);
const workspace=$('#workspace'),pangu=$('#pangu'),frame=$('#frozen-ui'),viewport=$('#ui-viewport'),canvas=$('#ui-canvas');
const reduced=matchMedia('(prefers-reduced-motion: reduce)'),mobile=matchMedia('(max-width: 700px)');
const steps={
 input:{title:'把模糊需求，变成可选择的输入。',copy:'行业、营销场景、产品主题、画面风格与平台规格共同组成生成需求，降低商户的描述门槛。',file:'pangu-create.png',focus:[245,80],mobileFocus:[245,80],zoom:1.6,next:'preview',label:'下一步：实时预览 →'},
 preview:{title:'先看到结果，再判断是否可用。',copy:'输入字段与青提柠檬成品预览在同一工作台，商户可以马上判断素材是否贴合实际营销场景。',file:'pangu-create.png',focus:[940,100],mobileFocus:[940,100],zoom:1.6,next:'assets',label:'下一步：沉淀与复用 →'},
 assets:{title:'把可用结果，沉淀为可复用的资产。',copy:'青提柠檬、抹茶奶冻与百香柠檬进入同一素材库，可筛选、收藏、下载和复用。',file:'pangu-library.png',focus:[245,100],mobileFocus:[245,100],zoom:1.08,next:'input',label:'重新看：结构化输入 ↺'}};
let scene='entry',step='input',timer,transitionId=0;
function setScene(value){scene=value;document.body.dataset.scene=value;}
function settleWorkspace(focus=true){clearTimeout(timer);setScene('workspace');workspace.inert=false;pangu.hidden=true;$('.home-control').hidden=true;window.scrollTo(0,0);if(focus)$('#workspace-title').focus({preventScroll:true});$('.scene-status').textContent='已进入工作现场。当前开放盘古智绘完整案例。';}
function enter(){if(scene!=='entry'){settleWorkspace();return;}setScene('entering');workspace.inert=true;pangu.hidden=true;const id=++transitionId;timer=setTimeout(()=>{if(id===transitionId)settleWorkspace();},reduced.matches?0:mobile.matches?780:1280);}
function openPangu(){clearTimeout(timer);++transitionId;workspace.inert=true;pangu.hidden=false;setScene('pangu');$('.home-control').hidden=false;window.scrollTo(0,0);$('#pangu-title').focus({preventScroll:true});requestAnimationFrame(()=>selectStep(step));$('.scene-status').textContent='盘古智绘。结构化输入、实时预览、素材沉淀与复用。';}
function entry(){clearTimeout(timer);++transitionId;setScene('entry');workspace.inert=true;pangu.hidden=true;$('.home-control').hidden=true;window.scrollTo(0,0);$('#enter').focus({preventScroll:true});}
function route(initial=false){if(location.hash==='#pangu')openPangu();else if(location.hash==='#workspace'){if(initial)settleWorkspace(false);else enter();}else if(!initial)entry();}
addEventListener('hashchange',()=>route());
document.addEventListener('click',event=>{const link=event.target.closest('a[href^="#"]');if(!link)return;const href=link.getAttribute('href');if(!['#entry','#workspace','#pangu'].includes(href))return;event.preventDefault();if(location.hash===href)route();else location.hash=href;});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&scene==='pangu')location.hash='#workspace';else if(event.key==='Escape'&&scene==='entering'){++transitionId;settleWorkspace();}});
function layoutUI(){if(scene!=='pangu')return;const data=steps[step],scale=mobile.matches ? .72 : Math.max(viewport.clientWidth/1536*data.zoom,.82),width=1536*scale,height=1024*scale;canvas.style.width=`${width}px`;canvas.style.height=`${height}px`;canvas.dataset.step=step;canvas.dataset.focusX=String(data.focus[0]);canvas.dataset.focusY=String(data.focus[1]);frame.style.transform=`scale(${scale})`;viewport.style.height=mobile.matches?'400px':`${Math.min(Math.max(430,innerHeight*.64),680)}px`;const focus=mobile.matches?data.mobileFocus:data.focus;const maxLeft=Math.max(0,width-viewport.clientWidth),maxTop=Math.max(0,height-viewport.clientHeight);viewport.scrollTo({left:Math.min(focus[0]*scale,maxLeft),top:Math.min(focus[1]*scale,maxTop),behavior:'instant'});$('#ui-hint').textContent=step==='input'?'真实产品界面 · 聚焦结构化字段 · 可滚动探索':step==='preview'?'同一产品界面 · 聚焦青提柠檬预览 · 可滚动探索':'真实素材库 · 筛选、收藏、下载与复用 · 可滚动探索';}
function selectStep(value,focus=false){step=value;const data=steps[value];document.querySelectorAll('[role="tab"]').forEach(tab=>{const active=tab.dataset.step===value;tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1;if(active&&focus)tab.focus();});$('#product-panel').setAttribute('aria-labelledby',`tab-${value}`);$('#step-title').textContent=data.title;$('#step-copy').textContent=data.copy;$('#next-step').textContent=data.label;$('.original-link').href=`assets/${data.file}`;$('.original-link').textContent='查看原始截图 ↗';frame.alt=value==='assets'?'盘古智绘我的素材界面，青提柠檬、抹茶奶冻与百香柠檬素材及资产管理操作':'盘古智绘新建素材生成界面，当前镜头聚焦'+(value==='input'?'左侧结构化输入字段':'右侧青提柠檬实时预览');const src=`assets/${data.file}`;if(frame.getAttribute('src')!==src){$('#ui-loading').hidden=false;frame.src=src;}layoutUI();}
document.querySelectorAll('[role="tab"]').forEach((tab,index,tabs)=>{tab.addEventListener('click',()=>selectStep(tab.dataset.step));tab.addEventListener('keydown',event=>{let next=index;if(event.key==='ArrowRight')next=(index+1)%tabs.length;else if(event.key==='ArrowLeft')next=(index+tabs.length-1)%tabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=tabs.length-1;else return;event.preventDefault();selectStep(tabs[next].dataset.step,true);});});
$('#next-step').addEventListener('click',()=>selectStep(steps[step].next));
frame.addEventListener('load',()=>{$('#ui-loading').hidden=true;layoutUI();});
const observer=new ResizeObserver(()=>layoutUI());observer.observe(viewport);mobile.addEventListener('change',()=>layoutUI());reduced.addEventListener('change',()=>{if(scene==='entering')settleWorkspace();});route(true);
if(frame.complete&&frame.naturalWidth>0)$('#ui-loading').hidden=true;
