const boot=document.querySelector('#boot'),portal=document.querySelector('#portal'),space=document.querySelector('#workspace'),surface=document.querySelector('#surface'),lines=document.querySelector('#lines'),enter=document.querySelector('#enter');
const mobile=()=>matchMedia('(max-width:700px),(pointer:coarse)').matches,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;let visited=false;try{visited=!!localStorage.getItem('cuiliya_workspace_visited_v1')}catch{}let launched=false,z=10,timers=[];
const intro=[['dim','正在打开 · 崔丽娅的 AI 产品工作空间'],['','崔丽娅 / 2027 届'],['dim','AI 产品运营 / 产品运营 / AI 应用产品'],['headline','把 AI 能力，做进真实工作里。'],['dim','已载入：盘古智绘 · 小红书内容运营 · NoteGuard AI'],['','请选择一个项目，开始探索。']];intro.forEach(([cls,text],i)=>{let p=document.createElement('p');p.className=cls;p.textContent=text;lines.append(p);if(visited||reduced)p.classList.add('visible');else timers.push(setTimeout(()=>p.classList.add('visible'),150+i*320))});
function reveal(){timers.forEach(clearTimeout);lines.querySelectorAll('p').forEach(p=>p.classList.add('visible'))}document.querySelector('#skip').onclick=reveal;
function launch(){if(launched)return;launched=true;reveal();try{localStorage.setItem('cuiliya_workspace_visited_v1','1')}catch{}boot.classList.add('launching');portal.querySelector('.progress i').style.width='100%';setTimeout(()=>{const r=portal.getBoundingClientRect();const scale=Math.max(innerWidth/r.width,innerHeight/r.height)*1.08;portal.style.transform=`scale(${scale})`;portal.style.opacity='0';space.hidden=false;setTimeout(()=>space.classList.add('visible'),reduced?0:300);setTimeout(()=>{boot.hidden=true;boot.style.display='none';document.querySelector('[data-open=pangu]').focus({preventScroll:true})},reduced?0:1400)},reduced?0:750)}enter.onclick=launch;document.addEventListener('keydown',e=>{if(e.key==='Enter'&&!launched){e.preventDefault();launch()}if(e.key==='Escape'){const wins=[...document.querySelectorAll('.window:not(.minimized)')].sort((a,b)=>Number(b.style.zIndex)-Number(a.style.zIndex));if(wins[0])closeWindow(wins[0])}});if(visited)timers.push(setTimeout(launch,700));
const titles={pangu:'盘古智绘',xhs:'小红书内容运营',ng:'NoteGuard AI',method:'我的工作方式'};const openWindows=new Map();
function syncDock(){document.querySelectorAll('#dock button').forEach(b=>{const w=openWindows.get(b.dataset.open);b.classList.toggle('active',!!w);b.classList.toggle('minimized',!!w?.classList.contains('minimized'))})}
function closeWindow(w){let id=w.dataset.id;openWindows.delete(id);w.remove();syncDock();document.querySelector(`.desktop-item[data-open="${id}"]`)?.focus({preventScroll:true})}
function front(w){w.style.zIndex=++z;w.classList.remove('minimized');syncDock()}
function openWindow(id){if(openWindows.has(id)){front(openWindows.get(id));return}const w=document.createElement('section');w.className='window';w.dataset.id=id;w.setAttribute('role','dialog');w.setAttribute('aria-label',titles[id]);w.innerHTML=`<div class="window-bar"><strong>${titles[id]}</strong><button data-action="min" aria-label="最小化">−</button><button data-action="max" aria-label="放大或还原">□</button><button data-action="close" aria-label="关闭窗口">×</button></div><div class="window-content"></div><div class="resize-handle" aria-hidden="true"></div>`;w.querySelector('.window-content').append(document.querySelector('#'+id).content.cloneNode(true));const offset=openWindows.size*24;w.style.left=Math.max(12,Math.min(surface.clientWidth-800,surface.clientWidth*.22)+offset)+'px';w.style.top=(20+offset)+'px';document.querySelector('#windows').append(w);openWindows.set(id,w);front(w);w.addEventListener('pointerdown',()=>front(w));w.querySelector('[data-action=close]').onclick=()=>closeWindow(w);w.querySelector('[data-action=min]').onclick=()=>{w.classList.add('minimized');syncDock();document.querySelector(`#dock [data-open=${id}]`).focus()};w.querySelector('[data-action=max]').onclick=()=>w.classList.toggle('maximized');bindDrag(w);w.querySelector('[data-action=close]').focus({preventScroll:true})}
function bindDrag(w){const bar=w.querySelector('.window-bar');bar.addEventListener('pointerdown',e=>{if(mobile()||w.classList.contains('maximized')||e.target.closest('button'))return;e.preventDefault();const x=e.clientX,y=e.clientY,l=w.offsetLeft,t=w.offsetTop;bar.setPointerCapture(e.pointerId);const move=v=>{w.style.left=Math.max(0,Math.min(surface.clientWidth-w.offsetWidth,l+v.clientX-x))+'px';w.style.top=Math.max(0,Math.min(surface.clientHeight-45,t+v.clientY-y))+'px'};bar.addEventListener('pointermove',move);const end=()=>{bar.removeEventListener('pointermove',move);bar.removeEventListener('pointerup',end);bar.removeEventListener('pointercancel',end)};bar.addEventListener('pointerup',end);bar.addEventListener('pointercancel',end)});const h=w.querySelector('.resize-handle');h.addEventListener('pointerdown',e=>{if(mobile())return;e.preventDefault();const x=e.clientX,y=e.clientY,sw=w.offsetWidth,sh=w.offsetHeight;h.setPointerCapture(e.pointerId);let move=v=>{w.style.width=Math.min(surface.clientWidth-w.offsetLeft,Math.max(380,sw+v.clientX-x))+'px';w.style.height=Math.min(surface.clientHeight-w.offsetTop,Math.max(240,sh+v.clientY-y))+'px'};h.addEventListener('pointermove',move);const end=()=>{h.removeEventListener('pointermove',move);h.removeEventListener('pointerup',end);h.removeEventListener('pointercancel',end)};h.addEventListener('pointerup',end);h.addEventListener('pointercancel',end)})}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openWindow(b.dataset.open));document.querySelector('#reset').onclick=()=>{try{localStorage.removeItem('cuiliya_workspace_visited_v1')}catch{}location.reload()};function clock(){document.querySelector('#clock').textContent=new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}clock();setInterval(clock,30000);window.addEventListener('resize',()=>{if(mobile())return;openWindows.forEach(w=>{w.style.left=Math.max(0,Math.min(w.offsetLeft,surface.clientWidth-w.offsetWidth))+'px';w.style.top=Math.max(0,Math.min(w.offsetTop,surface.clientHeight-45))+'px'})});
