const boot=document.querySelector('#boot'),portal=document.querySelector('#portal'),space=document.querySelector('#workspace'),surface=document.querySelector('#surface'),lines=document.querySelector('#lines'),enter=document.querySelector('#enter');
const mobile=()=>matchMedia('(max-width:700px),(pointer:coarse)').matches,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;let visited=false;try{visited=!!localStorage.getItem('cuiliya_workspace_visited_v1')}catch{}let launched=false,z=10,timers=[];
const intro=[['dim','AI 产品运营 / 产品运营 / AI 应用产品'],['headline','把 AI 能力，做进真实工作里。'],['dim','三个项目已加载']];intro.forEach(([cls,text],i)=>{let p=document.createElement('p');p.className=cls;p.textContent=text;lines.append(p);if(visited||reduced)p.classList.add('visible');else timers.push(setTimeout(()=>p.classList.add('visible'),150+i*320))});
function reveal(){timers.forEach(clearTimeout);lines.querySelectorAll('p').forEach(p=>p.classList.add('visible'))}document.querySelector('#skip').onclick=reveal;
function launch(){
 if(launched)return;launched=true;reveal();try{localStorage.setItem('cuiliya_workspace_visited_v1','1')}catch{}
 boot.classList.add('launching');portal.querySelector('.progress i').style.width='100%';
 if(reduced){space.hidden=false;space.classList.add('visible');boot.hidden=true;boot.style.display='none';return}
 setTimeout(()=>{
  const r=portal.getBoundingClientRect(),world=document.createElement('div');world.className='portal-world';world.setAttribute('aria-hidden','true');world.inert=true;
  const copy=space.cloneNode(true);copy.hidden=false;copy.classList.add('visible');copy.style.width=innerWidth+'px';copy.style.height=innerHeight+'px';const fit=Math.max((r.width-18)/innerWidth,(r.height-18)/innerHeight);copy.style.transform=`translate(${((r.width-18)-innerWidth*fit)/2}px,${((r.height-18)-innerHeight*fit)/2}px) scale(${fit})`;world.append(copy);portal.append(world);
  boot.classList.add('penetrating');requestAnimationFrame(()=>world.classList.add('visible'));
  setTimeout(()=>{const scale=Math.max(innerWidth/r.width,innerHeight/r.height)*1.03;const tx=innerWidth/2-(r.left+r.width/2),ty=innerHeight/2-(r.top+r.height/2);portal.style.transform=`translate3d(${tx}px,${ty}px,0) scale(${scale})`;portal.style.borderColor='#e5e9dc';},230);
  setTimeout(()=>{space.hidden=false;space.classList.add('workspace-entering','visible');boot.style.opacity='0';boot.style.transition='opacity .16s';setTimeout(()=>{boot.hidden=true;boot.style.display='none';world.remove();space.querySelector('.primary-project').focus({preventScroll:true})},160)},1770);
 },600)
}enter.onclick=launch;document.addEventListener('keydown',e=>{if(e.key==='Enter'&&!launched){e.preventDefault();launch()}if(e.key==='Escape'){const wins=[...document.querySelectorAll('.window:not(.minimized)')].sort((a,b)=>Number(b.style.zIndex)-Number(a.style.zIndex));if(wins[0])closeWindow(wins[0])}});if(visited)timers.push(setTimeout(launch,700));
const titles={pangu:'盘古智绘',xhs:'小红书内容运营',ng:'NoteGuard AI',method:'我的工作方式'};const openWindows=new Map();
function syncDock(){document.querySelectorAll('#dock button').forEach(b=>{const w=openWindows.get(b.dataset.open);b.classList.toggle('active',!!w);b.classList.toggle('minimized',!!w?.classList.contains('minimized'))})}
function closeWindow(w){space.classList.remove('dock-hidden');let id=w.dataset.id;openWindows.delete(id);w.remove();syncDock();document.querySelector(`#workspace [data-open="${id}"]`)?.focus({preventScroll:true})}
function front(w){w.style.zIndex=++z;w.classList.remove('minimized');syncDock()}
function openWindow(id){space.classList.remove('dock-hidden');if(openWindows.has(id)){front(openWindows.get(id));return}const w=document.createElement('section');w.className='window';w.dataset.id=id;w.setAttribute('role','dialog');w.setAttribute('aria-label',titles[id]);w.innerHTML=`<div class="window-bar"><strong>${titles[id]}</strong><button data-action="min" aria-label="最小化">−</button><button data-action="max" aria-label="放大或还原">□</button><button data-action="close" aria-label="关闭窗口">×</button></div><div class="window-content"></div><div class="resize-handle" aria-hidden="true"></div>`;w.querySelector('.window-content').append(document.querySelector('#'+id).content.cloneNode(true));const offset=openWindows.size*24;w.style.left=Math.max(12,Math.min(surface.clientWidth-800,surface.clientWidth*.22)+offset)+'px';w.style.top=(20+offset)+'px';document.querySelector('#windows').append(w);openWindows.set(id,w);front(w);w.addEventListener('pointerdown',()=>front(w));w.querySelector('[data-action=close]').onclick=()=>closeWindow(w);w.querySelector('[data-action=min]').onclick=()=>{w.classList.add('minimized');syncDock();document.querySelector(`#dock [data-open=${id}]`).focus()};w.querySelector('[data-action=max]').onclick=()=>w.classList.toggle('maximized');bindDrag(w);bindContent(w,id);w.querySelector('[data-action=close]').focus({preventScroll:true})}
function bindDrag(w){const bar=w.querySelector('.window-bar');bar.addEventListener('pointerdown',e=>{if(mobile()||w.classList.contains('maximized')||e.target.closest('button'))return;e.preventDefault();const x=e.clientX,y=e.clientY,l=w.offsetLeft,t=w.offsetTop;bar.setPointerCapture(e.pointerId);const move=v=>{w.style.left=Math.max(0,Math.min(surface.clientWidth-w.offsetWidth,l+v.clientX-x))+'px';w.style.top=Math.max(0,Math.min(surface.clientHeight-45,t+v.clientY-y))+'px'};bar.addEventListener('pointermove',move);const end=()=>{bar.removeEventListener('pointermove',move);bar.removeEventListener('pointerup',end);bar.removeEventListener('pointercancel',end)};bar.addEventListener('pointerup',end);bar.addEventListener('pointercancel',end)});const h=w.querySelector('.resize-handle');h.addEventListener('pointerdown',e=>{if(mobile())return;e.preventDefault();const x=e.clientX,y=e.clientY,sw=w.offsetWidth,sh=w.offsetHeight;h.setPointerCapture(e.pointerId);let move=v=>{w.style.width=Math.min(surface.clientWidth-w.offsetLeft,Math.max(380,sw+v.clientX-x))+'px';w.style.height=Math.min(surface.clientHeight-w.offsetTop,Math.max(240,sh+v.clientY-y))+'px'};h.addEventListener('pointermove',move);const end=()=>{h.removeEventListener('pointermove',move);h.removeEventListener('pointerup',end);h.removeEventListener('pointercancel',end)};h.addEventListener('pointerup',end);h.addEventListener('pointercancel',end)})}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openWindow(b.dataset.open));document.querySelector('#reset').onclick=()=>{try{localStorage.removeItem('cuiliya_workspace_visited_v1')}catch{}location.reload()};function clock(){document.querySelector('#clock').textContent=new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}clock();setInterval(clock,30000);window.addEventListener('resize',()=>{if(mobile())return;openWindows.forEach(w=>{w.style.left=Math.max(0,Math.min(w.offsetLeft,surface.clientWidth-w.offsetWidth))+'px';w.style.top=Math.max(0,Math.min(w.offsetTop,surface.clientHeight-45))+'px'})});

const workflowData=[
 ['盘古智绘 / 内容业务','先找到真实的操作门槛。','商户难以描述画面，内容运营需要判断表达风险。先从业务一线的问题出发，再决定 AI 应当承担什么。','pangu','打开盘古工作现场'],
 ['NoteGuard / AI 协作','把模糊诉求拆成可验证的任务。','与 AI 协作拆解风险识别、建议生成、人工确认和复检。明确哪些内容能自动处理，哪些判断必须留给人。','ng','打开 NoteGuard'],
 ['盘古 / NoteGuard','让方案变成可操作的原型。','盘古用六字段降低输入门槛；NoteGuard 通过原型和 Vibe Coding 验证人机协作。页面能运行之后，继续检查用户是否能完成任务。','pangu','查看冻结盘古原型'],
 ['NoteGuard / GitHub','每次迭代，都能追溯到版本。','通过 GitHub 保留代码与迭代记录，把工作流和规则语义仲裁放在明确的分支中，先验证再合并。','github','查看版本记录'],
 ['盘古 A/B / NoteGuard 冻结评测','先定义验证方式，再看结果。','盘古通过三轮 A/B 迭代；NoteGuard 使用 80 条冻结测试，比较规则层与完整系统。内部测试和真实用户验证分开解读。','ng','查看评测证据'],
 ['NoteGuard / 真实试用','“识别准确”之外，还要看采用。','6 名目标用户试用 36 条真实或脱敏内容，29 条建议被直接采用或修改后采用。采用率 80.6%，用于验证建议是否进入真实工作。','ng','查看用户验证'],
 ['问题回溯 / 再次验证','把失败变成下一次迭代的输入。','规则层暴露语境误判后，迭代规则与语义仲裁；采用后的文本再复检。每次改动都回到明确问题与验证证据。','ng','查看迭代结构']
];
const ngData={baseline:'<small>01 / 冻结测试基线</small><h3>只靠规则，还不够。</h3><div class="big-evidence">51.25%</div><p>80 条冻结内部测试：40 条风险、40 条安全。规则层仅识别 7 / 40 条风险，关键词命中也可能忽略否定、引用和合规提醒。</p>',architecture:'<small>02 / 规则与语义仲裁</small><h3>明确风险保留，语境交给复核。</h3><div class="architecture"><section><b>高置信硬规则</b><p>明确风险直接拦截，保留规则的确定性。</p></section><section><b>上下文型命中</b><p>否定、引用、合规提醒等语境交给语义层复核。</p></section></div><div class="architecture-footer">原文与建议稿分离 · 人工确认采用 · 采用后的最终文本再复检<br>此处已预留逐层架构展开，下一阶段再加入完整演示。</div>',users:'<small>04 / 真实用户验证</small><h3>让建议真正进入工作。</h3><div class="big-evidence">80.6%</div><p>6 名目标用户 · 36 条真实 / 脱敏内容<br>29 条建议被直接采用或修改后采用。<br>这是小样本采用验证，与内部 80 条分类评测分别统计。</p>'};
function bindContent(w,id){
 if(id==='method')w.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{w.querySelectorAll('[data-stage]').forEach(x=>x.classList.toggle('selected',x===b));let [label,title,desc,target,cta]=workflowData[Number(b.dataset.stage)],panel=w.querySelector('.workflow-evidence');panel.innerHTML=`<small>${label}</small><h3>${title}</h3><p>${desc}</p>`;const a=document.createElement(target==='github'?'a':'button');a.textContent=cta+' ↗';if(target==='github'){a.href='https://github.com/cuiliya521/NoteGuard-AI';a.target='_blank';a.rel='noreferrer'}else a.onclick=()=>openWindow(target);panel.append(a);if(Number(b.dataset.stage)===2){const img=document.createElement('img');img.src='assets/pangu-frozen-product.webp';img.alt='盘古智绘冻结产品原型';panel.append(img)}});
 if(id==='method')w.querySelector('[data-open]')?.addEventListener('click',()=>openWindow('pangu'));
 if(id==='ng')w.querySelectorAll('[data-ng-stage]').forEach(b=>b.onclick=()=>{w.querySelectorAll('[data-ng-stage]').forEach(x=>x.classList.toggle('selected',x===b));let key=b.dataset.ngStage,p=w.querySelector('.ng-stage-panel');p.innerHTML=ngData[key]||'';p.classList.toggle('shown',key!=='system');w.querySelector('.test-evidence').hidden=key!=='system'});
 const content=w.querySelector('.window-content');let last=0;content.addEventListener('scroll',()=>{if(!mobile())return;const now=content.scrollTop;if(now>last&&now>70)space.classList.add('dock-hidden');last=now},{passive:true});
}
const toggle=document.createElement('button');toggle.className='dock-toggle';toggle.textContent='项目导航 ↑';toggle.onclick=()=>space.classList.remove('dock-hidden');space.append(toggle);

// One viewer: switching previews does not open or stack project windows.
const projectIds=['pangu','xhs','ng'];let selectedProject='pangu';
const projectPreviews={
 pangu:{title:'盘古智绘',judgment:'把 Prompt 变成商户会选的字段。',visual:'<img src="assets/pangu-frozen-product.webp" alt="盘古智绘冻结产品原型">'},
 xhs:{title:'小红书内容运营',judgment:'让 AI 卖点变成家长能感知的场景。',visual:'<div class="post-pending"><small>主案例 · 原图待接入</small><p>我们班已经有人<br>开始用 AI 一对一了</p><span>保留真实帖子素材位</span></div>'},
 ng:{title:'NoteGuard AI',judgment:'识别风险之后，让人敢用 AI 的建议。',visual:'<div class="ng-viewer"><small>NoteGuard AI / V5</small><p>AI 建议，<br>由人确认采用。</p><span>风险识别 · 人工确认 · 采用后复检</span></div>'}
};
const projectTabs=[...document.querySelectorAll('[data-project]')],viewer=document.querySelector('.project-viewer');
function selectProject(id){if(id===selectedProject)return;selectedProject=id;const p=projectPreviews[id];projectTabs.forEach(b=>{const active=b.dataset.project===id;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1});document.querySelector('#project-panel').setAttribute('aria-labelledby','tab-'+id);document.querySelector('#viewer-title').textContent=p.title;document.querySelector('#viewer-judgment').textContent=p.judgment;document.querySelector('#viewer-visual').innerHTML=p.visual;document.querySelector('#open-project').dataset.open=id;viewer.dataset.project=id;}
projectTabs.forEach(b=>{b.onclick=()=>selectProject(b.dataset.project);b.addEventListener('pointerenter',()=>{if(matchMedia('(hover:hover) and (pointer:fine)').matches)selectProject(b.dataset.project)});b.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const current=projectIds.indexOf(b.dataset.project);const index=e.key==='Home'?0:e.key==='End'?2:(current+(e.key==='ArrowRight'?1:2))%3;selectProject(projectIds[index]);projectTabs[index].focus()})});
let touchStart=null;const visual=document.querySelector('#viewer-visual');visual.addEventListener('touchstart',e=>{touchStart={x:e.changedTouches[0].clientX,y:e.changedTouches[0].clientY}},{passive:true});visual.addEventListener('touchend',e=>{if(!touchStart)return;const dx=e.changedTouches[0].clientX-touchStart.x,dy=e.changedTouches[0].clientY-touchStart.y;touchStart=null;if(Math.abs(dx)<55||Math.abs(dx)<Math.abs(dy)*1.3)return;const index=(projectIds.indexOf(selectedProject)+(dx<0?1:2))%3;selectProject(projectIds[index])},{passive:true});
