const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs/promises');
(async()=>{const browser=await chromium.launch({headless:true});const results=[];await fs.mkdir('desk-qa',{recursive:true});
for(const [name,w,h,motion] of [['desktop',1440,900,'no-preference'],['laptop',1280,800,'no-preference'],['mobile',390,844,'no-preference'],['small-mobile',360,740,'no-preference'],['reduced',1440,900,'reduce']]){
 const ctx=await browser.newContext({viewport:{width:w,height:h},isMobile:w<701,hasTouch:w<701,reducedMotion:motion});const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:4173',{waitUntil:'networkidle'});await page.screenshot({path:`desk-qa/${name}-entry.png`});await page.locator('#enter').click();await page.locator('body[data-scene="workspace"]').waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollHeight>innerHeight+1),false,'workspace is one viewport');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'no horizontal overflow');
 if(w>700){const bounds=await page.locator('.work-surface > article,.work-surface > aside').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {name:e.dataset.object,x:r.x,y:r.y,right:r.right,bottom:r.bottom};}));for(const r of bounds){assert(r.x>=0&&r.y>=0&&r.right<=w&&r.bottom<=h,JSON.stringify(r));}results.push({name,bounds});
 await page.locator('.noteguard-object .desk-open').click();await page.locator('dialog[open]').waitFor();assert.match(await page.locator('.focus-content').innerText(),/96.25/);await page.keyboard.press('Escape');assert.equal(await page.locator('dialog').evaluate(e=>e.open),false);
 }else{for(let i=0;i<5;i++){await page.locator('.scene-nav button').nth(i).click();const active=page.locator('.work-surface > [data-active="true"]');assert.equal(await active.count(),1);const r=await active.boundingBox();assert(r.x>=0&&r.x+r.width<=w+1&&r.y+r.height<=h,JSON.stringify(r));await page.screenshot({path:`desk-qa/${name}-object${i}.png`});}await page.locator('.scene-nav button').first().click();const metric=await page.locator('.pangu-result strong').boundingBox();assert(metric.x+metric.width<=w,'metric not clipped');results.push({name,metric});}
 await page.screenshot({path:`desk-qa/${name}-workspace.png`});await page.locator('#open-pangu').click();await page.locator('body[data-scene="pangu"]').waitFor();if(w<701){const r=await page.locator('.case-result strong').boundingBox();assert(r.x+r.width<=w,'case metric not clipped');}await page.locator('.back-link').click();await page.locator('body[data-scene="workspace"]').waitFor();assert.deepEqual(errors,[]);await ctx.close();
}await fs.writeFile('desk-qa/results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
