/* Run with Playwright installed, QA_URL pointing to a Preview or local server. */
const {chromium}=require('playwright');
const fs=require('node:fs/promises');
const assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({headless:true});
const output=process.env.QA_OUTPUT||'qa-output';await fs.mkdir(output,{recursive:true});
const results=[];
for(const [name,width,height,touch,reduced] of [['desktop',1440,900,false,false],['laptop',1280,800,false,false],['mobile',390,844,true,false],['reduced',1440,900,false,true]]){
const context=await browser.newContext({viewport:{width,height},hasTouch:touch,isMobile:touch,reducedMotion:reduced?'reduce':'no-preference'});
const page=await context.newPage(),errors=[],failures=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failures.push({url:r.url(),status:r.status()});});
await page.goto(process.env.QA_URL||'http://127.0.0.1:4173',{waitUntil:'networkidle'});
assert.equal(await page.locator('body').getAttribute('data-scene'),'entry');
assert.equal(await page.locator('#workspace').evaluate(e=>e.inert),true);
await page.screenshot({path:`${output}/${name}-entry.png`});
await page.locator('#enter').click();
await page.locator('body[data-scene="workspace"]').waitFor();
assert.equal(await page.locator('#workspace').evaluate(e=>e.inert),false);
await page.screenshot({path:`${output}/${name}-workspace.png`,fullPage:true});
const wsOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);
assert.equal(wsOverflow,false,'workspace horizontal overflow');
await page.locator('#open-pangu').click();
await page.locator('body[data-scene="pangu"]').waitFor();
await page.locator('#ui-loading').waitFor({state:'hidden'});
await page.screenshot({path:`${output}/${name}-pangu-input.png`,fullPage:true});
const panguOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);
assert.equal(panguOverflow,false,'case horizontal overflow');
const productImage=page.locator('#frozen-ui');
assert.equal(await productImage.getAttribute('src'),'assets/pangu-create.png');
assert.equal(await productImage.evaluate(e=>e.complete&&e.naturalWidth===1536&&e.naturalHeight===1024),true,'supplied create screen decode');
const cameraInput=await page.locator('#ui-viewport').evaluate(e=>({left:e.scrollLeft,top:e.scrollTop,scale:parseFloat(getComputedStyle(document.querySelector('#frozen-ui')).transform.match(/matrix\(([^,]+)/)?.[1]||'1')}));
const inputRegion=await page.locator('#ui-viewport').evaluate(e=>({center:(e.scrollLeft+e.clientWidth/2)/parseFloat(getComputedStyle(document.querySelector('#frozen-ui')).transform.match(/matrix\(([^,]+)/)?.[1]||'1')}));
assert(inputRegion.center>245&&inputRegion.center<900,'01 viewport centers on structured fields');
await page.locator('#tab-input').focus();await page.keyboard.press('ArrowRight');
assert.equal(await page.locator('#tab-preview').getAttribute('aria-selected'),'true');
assert.equal(await page.locator('#tab-preview').evaluate(e=>e===document.activeElement),true);
assert.equal(await productImage.getAttribute('src'),'assets/pangu-create.png','01 and 02 use the same supplied screen');
const cameraPreview=await page.locator('#ui-viewport').evaluate(e=>({left:e.scrollLeft,top:e.scrollTop}));
assert.notEqual(cameraPreview.left,cameraInput.left,'01 and 02 move the camera horizontally');
const previewCenter=await page.locator('#ui-canvas').evaluate(e=>({focus:Number(e.dataset.focusX),scroll:document.querySelector('#ui-viewport').scrollLeft,scale:parseFloat(getComputedStyle(document.querySelector('#frozen-ui')).transform.match(/matrix\(([^,]+)/)?.[1]||'1'),width:document.querySelector('#ui-viewport').clientWidth}));
assert(previewCenter.scroll+previewCenter.width/2>=900*previewCenter.scale,'02 viewport centers on the Qingti preview region');
await page.screenshot({path:`${output}/${name}-pangu-preview.png`,fullPage:true});
await page.locator('#next-step').click();await page.locator('#ui-loading').waitFor({state:'hidden'});
assert.equal(await page.locator('#frozen-ui').getAttribute('src'),'assets/pangu-library.png');
assert.match(await page.locator('#frozen-ui').getAttribute('alt'),/我的素材/);
await page.screenshot({path:`${output}/${name}-pangu-assets.png`,fullPage:true});
assert.equal(await productImage.evaluate(e=>e.complete&&e.naturalWidth===1536&&e.naturalHeight===1024),true,'supplied asset library screen decode');
const assetFrame=await page.locator('#ui-viewport').evaluate(e=>({left:e.scrollLeft,scale:parseFloat(getComputedStyle(document.querySelector('#frozen-ui')).transform.match(/matrix\(([^,]+)/)?.[1]||'1'),width:e.clientWidth}));
assert(assetFrame.left/assetFrame.scale<=280&&(assetFrame.left+assetFrame.width)/assetFrame.scale>680,'03 viewport includes the first asset card');
if(touch){const dims=await page.locator('#ui-viewport').evaluate(e=>({w:e.clientWidth,sw:e.scrollWidth,left:e.scrollLeft,top:e.scrollTop}));assert(dims.sw>dims.w,'mobile UI can pan');assert(dims.left>0,'mobile focus offset applied');}
await page.keyboard.press('Escape');await page.locator('body[data-scene="workspace"]').waitFor();
await page.goBack();await page.locator('body[data-scene="pangu"]').waitFor();
await page.goto((process.env.QA_URL||'http://127.0.0.1:4173')+'/#workspace');await page.locator('body[data-scene="workspace"]').waitFor();
await page.locator('.identity').click();await page.locator('body[data-scene="entry"]').waitFor();
await page.locator('#enter').click();if(!reduced)await page.keyboard.press('Escape');await page.locator('body[data-scene="workspace"]').waitFor();
const image=await page.locator('.product-image-wrap img').evaluate(e=>({naturalWidth:e.naturalWidth,renderedWidth:e.clientWidth,complete:e.complete}));
assert(image.complete&&image.naturalWidth>image.renderedWidth,'workspace source image sufficient resolution');
assert.deepEqual(errors,[],'page errors');assert.deepEqual(failures,[],'HTTP errors');
results.push({name,width,height,errors,failures,wsOverflow,panguOverflow,image});await context.close();
}
await fs.writeFile(`${output}/results.json`,JSON.stringify(results,null,2));console.log(JSON.stringify(results));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
